from .user import User
from .ataud import Ataud
from .capilla import Capilla
from .vehiculo import Vehiculo
from .fallecido import Fallecido
from .contratante import Contratante
from .servicio import Servicio
from .servicio_vehiculo import ServicioVehiculo
from .pasajero import Pasajero
from .pago import Pago